# Netlify configuration for domain consolidation and SEO optimization

[build]
  publish = "dist"
  command = "rm -rf dist node_modules/.cache node_modules/.astro .netlify/cache && npm ci && npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_SKIP_CACHE = "true"
  NETLIFY_CLEAR_CACHE = "true"
  BUILD_TIMESTAMP = "1756460357595"

# Domain consolidation redirects - Force apex domain for SEO authority
[[redirects]]
  from = "https://www.hairbymelissa.co.nz/*"
  to = "https://hairbymelissa.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.hairbymelissa.co.nz/*"
  to = "https://hairbymelissa.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://hairbymelissa.co.nz/*"
  to = "https://hairbymelissa.co.nz/:splat"
  status = 301
  force = true

# Alternative domain variations (if owned)
[[redirects]]
  from = "https://hairbymelissa.com/*"
  to = "https://hairbymelissa.co.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.hairbymelissa.com/*"
  to = "https://hairbymelissa.co.nz/:splat"
  status = 301
  force = true

# Legacy URL redirects for SEO
[[redirects]]
  from = "/book"
  to = "/booking/"
  status = 301

[[redirects]]
  from = "/appointment"
  to = "/booking/"
  status = 301

[[redirects]]
  from = "/prices"
  to = "/services/"
  status = 301

[[redirects]]
  from = "/treatments"
  to = "/services/"
  status = 301

# Service-specific redirects
[[redirects]]
  from = "/keratin"
  to = "/services/keratin-treatments/"
  status = 301

[[redirects]]
  from = "/highlights"
  to = "/services/full-head-highlights/"
  status = 301

[[redirects]]
  from = "/balayage"
  to = "/services/balayage/"
  status = 301

[[redirects]]
  from = "/cut"
  to = "/services/womens-cut-finish/"
  status = 301

[[redirects]]
  from = "/haircut"
  to = "/services/womens-cut-finish/"
  status = 301

[[redirects]]
  from = "/color"
  to = "/services/"
  status = 301

[[redirects]]
  from = "/colour"
  to = "/services/"
  status = 301

# Headers for security and SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Caching for performance (SEO factor)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# NUCLEAR: Disable ALL JavaScript file caching
[[headers]]
  for = "/_astro/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# URGENT: Block old JavaScript files to force cache invalidation
[[redirects]]
  from = "/_astro/Layout.astro_ast*.js"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/_astro/LoadingSpinner.astro_ast*.js"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/_astro/Navbar.astro_ast*.js"
  to = "/404"
  status = 404
  force = true

# EXTREME: Block ANY .js file in _astro directory
[[redirects]]
  from = "/_astro/*.js"
  to = "/404"
  status = 404
  force = true